server:
  port: "8080"
  host: "localhost"

api:
  base_url: "http://localhost:5000"  # URL для локального запуска
  timeout: 30s
  retry_count: 3

rabbitmq:
  url: "amqp://guest:guest@localhost:5672/"  # URL для локального RabbitMQ
  queue_name: "weather_data"

logging:
  level: "debug"  # Более подробное логирование для разработки


